### PR TITLE
change to support kibana 4.1.1

### PR DESCRIPTION
**Pull request by agonen**

### CODE REVIEW

**Comment by agonen** [comment]
change code to install 4.1.1

**Comment by burtonator** [comment]
Looks awesome but could you update your patch to not include the tar.gz and .jar files and other files in the target directory ?

Those aren't needed and will just bloat the repo.  

Thanks!

**Comment by agonen** [comment]
cleaned target directory .

**Comment by burtonator** [comment]
Awesome.  Merged!

**Pull request merged**
